#ifndef KLUSTERSSHARED_EXPORT_H
#define KLUSTERSSHARED_EXPORT_H

#include <QtCore/qglobal.h>

# ifdef KLUSTERSSHARED_STATICLIB
#  undef KLUSTERSSHARED_SHAREDLIB
#  define KLUSTERSSHARED_EXPORT
# else
#  ifdef KLUSTERSSHARED_BUILD_KLUSTERSSHARED_LIB
#   define KLUSTERSSHARED_EXPORT Q_DECL_EXPORT
#  else
#   define KLUSTERSSHARED_EXPORT Q_DECL_IMPORT
#  endif
# endif



#endif // KLUSTERSSHARED_EXPORT_H
